apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: da
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: dacentos
    name: dacentos
  spec:
    replicas: 1
    selector:
      app: dacentos
      deploymentconfig: dacentos
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: dacentos
          deploymentconfig: dacentos
      spec:
        containers:
        - env:
          - name: APPSERVER_PORT
            value: "8080"
          - name: BOF_REGISTRY_USER_PASSWORD
            value: password
          - name: CRYPTO_REGISTRY_DOCBASE_NAME
            value: centdb
          - name: DFC_SESSION_SECURE_CONNECT_DEFAULT
            value: try_secure_first
          - name: DOCBROKER_IP
            value: 10.128.4.25
          - name: DOCBROKER_PORT
            value: "1489"
          - name: GLOBAL_REGISTRY_DOCBASE_NAME
            value: centdb
          - name: PRESETS_PREFERENCES_USER_PASSWORD
            value: webtop
          image: 172.30.23.146:5000/bkttest/da_centos@sha256:8cdd79d416ac698c8112cc310ea50bb02ee0ab974d8908c8a0815881bb610562
          imagePullPolicy: IfNotPresent
          name: dacentos
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - dacentos
        from:
          kind: ImageStreamTag
          name: da_centos:7.3.0000.0074
          namespace: bkttest
      type: ImageChange
  parameters:
  - name: DOCBROKER_IP
    displayName: DocBroker Pod IP
    description: IP Address of the Content Server pod
    value: NULL
    required: true
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.name: dacentos-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: dacentos
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: image change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"dacentos","namespace":"bkttest","selfLink":"/oapi/v1/namespaces/bkttest/deploymentconfigs/dacentos","uid":"8065790e-ad3a-11e7-9bfb-fa163eed3f98","resourceVersion":"8427054","generation":2,"creationTimestamp":"2017-10-09T21:40:43Z","labels":{"app":"dacentos"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["dacentos"],"from":{"kind":"ImageStreamTag","namespace":"bkttest","name":"da_centos:7.3.0000.0074"},"lastTriggeredImage":"172.30.23.146:5000/bkttest/da_centos@sha256:8cdd79d416ac698c8112cc310ea50bb02ee0ab974d8908c8a0815881bb610562"}}],"replicas":1,"test":false,"selector":{"app":"dacentos","deploymentconfig":"dacentos"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"dacentos","deploymentconfig":"dacentos"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"containers":[{"name":"dacentos","image":"172.30.23.146:5000/bkttest/da_centos@sha256:8cdd79d416ac698c8112cc310ea50bb02ee0ab974d8908c8a0815881bb610562","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"}],"env":[{"name":"APPSERVER_PORT","value":"8080"},{"name":"BOF_REGISTRY_USER_PASSWORD","value":"password"},{"name":"CRYPTO_REGISTRY_DOCBASE_NAME","value":"centdb"},{"name":"DFC_SESSION_SECURE_CONNECT_DEFAULT","value":"try_secure_first"},{"name":"DOCBROKER_IP","value":"10.128.4.25"},{"name":"DOCBROKER_PORT","value":"1489"},{"name":"GLOBAL_REGISTRY_DOCBASE_NAME","value":"centdb"},{"name":"PRESETS_PREFERENCES_USER_PASSWORD","value":"webtop"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"ImageStreamTag","namespace":"bkttest","name":"da_centos:7.3.0000.0074"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2017-10-09T21:40:43Z","lastTransitionTime":"2017-10-09T21:40:43Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: null
    generation: 1
    labels:
      app: dacentos
      openshift.io/deployment-config.name: dacentos
    name: dacentos-1
  spec:
    replicas: 1
    selector:
      app: dacentos
      deployment: dacentos-1
      deploymentconfig: dacentos
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: dacentos
          openshift.io/deployment.name: dacentos-1
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: dacentos
          deployment: dacentos-1
          deploymentconfig: dacentos
      spec:
        containers:
        - env:
          - name: APPSERVER_PORT
            value: "8080"
          - name: BOF_REGISTRY_USER_PASSWORD
            value: password
          - name: CRYPTO_REGISTRY_DOCBASE_NAME
            value: centdb
          - name: DFC_SESSION_SECURE_CONNECT_DEFAULT
            value: try_secure_first
          - name: DOCBROKER_IP
            value: 10.128.4.25
          - name: DOCBROKER_PORT
            value: "1489"
          - name: GLOBAL_REGISTRY_DOCBASE_NAME
            value: centdb
          - name: PRESETS_PREFERENCES_USER_PASSWORD
            value: webtop
          image: 172.30.23.146:5000/bkttest/da_centos@sha256:8cdd79d416ac698c8112cc310ea50bb02ee0ab974d8908c8a0815881bb610562
          imagePullPolicy: IfNotPresent
          name: dacentos
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dacentos
    name: dacentos
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: dacentos
      deploymentconfig: dacentos
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"bkttest","name":"dacentos-1","uid":"806f0637-ad3a-11e7-8693-fa163e42e181","apiVersion":"v1","resourceVersion":"8427079"}}
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: dacentos
      openshift.io/deployment.name: dacentos-1
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/scc: anyuid
    creationTimestamp: null
    generateName: dacentos-1-
    labels:
      app: dacentos
      deployment: dacentos-1
      deploymentconfig: dacentos
  spec:
    containers:
    - env:
      - name: APPSERVER_PORT
        value: "8080"
      - name: BOF_REGISTRY_USER_PASSWORD
        value: password
      - name: CRYPTO_REGISTRY_DOCBASE_NAME
        value: centdb
      - name: DFC_SESSION_SECURE_CONNECT_DEFAULT
        value: try_secure_first
      - name: DOCBROKER_IP
        value: 10.128.4.25
      - name: DOCBROKER_PORT
        value: "1489"
      - name: GLOBAL_REGISTRY_DOCBASE_NAME
        value: centdb
      - name: PRESETS_PREFERENCES_USER_PASSWORD
        value: webtop
      image: 172.30.23.146:5000/bkttest/da_centos@sha256:8cdd79d416ac698c8112cc310ea50bb02ee0ab974d8908c8a0815881bb610562
      imagePullPolicy: IfNotPresent
      name: dacentos
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 8443
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - MKNOD
          - SYS_CHROOT
        privileged: false
        seLinuxOptions:
          level: s0:c10,c5
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-dqxr8
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-cg2tn
    nodeName: ocpnode-3.fortnebula.com
    nodeSelector:
      region: primary
    restartPolicy: Always
    securityContext:
      seLinuxOptions:
        level: s0:c10,c5
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: default-token-dqxr8
      secret:
        defaultMode: 420
        secretName: default-token-dqxr8
  status:
    phase: Pending
