apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: da
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: dacentos
    name: dacentos
  spec:
    replicas: 1
    selector:
      app: dacentos
      deploymentconfig: dacentos
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: dacentos
          deploymentconfig: dacentos
      spec:
        containers:
        - env:
          - name: APPSERVER_PORT
            value: "8080"
          - name: BOF_REGISTRY_USER_PASSWORD
            value: password
          - name: CRYPTO_REGISTRY_DOCBASE_NAME
            value: centdb
          - name: DFC_SESSION_SECURE_CONNECT_DEFAULT
            value: try_secure_first
          - name: DOCBROKER_IP
            value: '{DOCBROKER_IP}'
          - name: DOCBROKER_PORT
            value: "1489"
          - name: GLOBAL_REGISTRY_DOCBASE_NAME
            value: centdb
          - name: PRESETS_PREFERENCES_USER_PASSWORD
            value: webtop
          name: dacentos
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - dacentos
        from:
          kind: ImageStreamTag
          name: da_centos:7.3.0000.0074
          namespace: bkttest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: dacentos
    name: dacentos
  spec:
    path: /da
    port:
      targetPort: port-1
    to:
      kind: Service
      name: dacentos
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dacentos
    name: dacentos
  spec:
    ports:
    - name: port-1
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: port-2
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: dacentos
      deploymentconfig: dacentos
    sessionAffinity: None
    type: ClusterIP
parameters:
  - name: DOCBROKER_IP
    displayName: DocBroker Pod IP
    description: IP Address of the Content Server pod
    value: NULL
    required: true